# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-21 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='业务线名称')),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpuarch', models.CharField(blank=True, max_length=8, null=True, verbose_name='CPU位数')),
                ('num_cpus', models.CharField(blank=True, max_length=4, null=True, verbose_name='CPU核心数')),
                ('cpu_model', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU型号')),
            ],
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=16, null=True, verbose_name='挂载路径')),
                ('size', models.CharField(blank=True, max_length=8, null=True, verbose_name='磁盘大小/G')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=16, null=True, verbose_name='服务器主机名')),
                ('login_port', models.CharField(blank=True, max_length=4, null=True, verbose_name='ssh登录端口')),
                ('login_name', models.CharField(default='root', max_length=16, verbose_name='登录用户名')),
                ('login_pwd', models.CharField(blank=True, max_length=16, null=True, verbose_name='登录密码')),
                ('speed', models.IntegerField(blank=True, null=True, verbose_name='带宽/M')),
                ('uuid', models.CharField(blank=True, max_length=32, null=True, verbose_name='uuid')),
                ('kernel', models.CharField(blank=True, max_length=16, null=True, verbose_name='外网IP')),
                ('busnesses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Business', verbose_name='业务线')),
                ('cpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Cpu', verbose_name='CPU')),
                ('disk', models.ManyToManyField(blank=True, null=True, to='db.Disk', verbose_name='磁盘')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=4, null=True, verbose_name='内存/G')),
                ('width', models.CharField(blank=True, max_length=8, null=True, verbose_name='位数')),
                ('locator', models.CharField(blank=True, max_length=8, null=True, verbose_name='插槽')),
                ('type', models.CharField(blank=True, max_length=16, null=True, verbose_name='内存类型')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=64, null=True, verbose_name='主板sn')),
                ('manufacturer', models.CharField(blank=True, max_length=16, null=True, verbose_name='发行商')),
                ('pn', models.CharField(blank=True, max_length=16, null=True, verbose_name='厂商')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=16, null=True, verbose_name='IP地址')),
                ('mac_address', models.CharField(blank=True, max_length=16, null=True, verbose_name='MAC地址')),
            ],
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=8, null=True, verbose_name='系统名称')),
            ],
        ),
        migrations.CreateModel(
            name='Osarch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarch', models.CharField(blank=True, max_length=8, null=True, verbose_name='位数')),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='用途名称')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='来源')),
            ],
        ),
        migrations.CreateModel(
            name='SvnFunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='动作')),
            ],
        ),
        migrations.CreateModel(
            name='SvnUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Svn地址')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=16, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=32, null=True, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=8, null=True, verbose_name='人名')),
                ('job', models.CharField(blank=True, max_length=8, null=True, verbose_name='职位')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='eth0_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eth0', to='db.Network', verbose_name='外网IP'),
        ),
        migrations.AddField(
            model_name='host',
            name='eth1_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eth1', to='db.Network', verbose_name='内网IP'),
        ),
        migrations.AddField(
            model_name='host',
            name='mem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Memory', verbose_name='MEM/G'),
        ),
        migrations.AddField(
            model_name='host',
            name='motherboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Motherboard', verbose_name='主板'),
        ),
        migrations.AddField(
            model_name='host',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Os', verbose_name='操作系统'),
        ),
        migrations.AddField(
            model_name='host',
            name='osarch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Osarch', verbose_name='系统位数'),
        ),
        migrations.AddField(
            model_name='host',
            name='purposes',
            field=models.ManyToManyField(blank=True, null=True, to='db.Purpose', verbose_name='机器用途'),
        ),
        migrations.AddField(
            model_name='host',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Source', verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='host',
            name='the_fater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fater', to='db.Host', verbose_name='宿主机'),
        ),
    ]
