# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-04 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_userinfo_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='pn',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='厂商'),
        ),
    ]
