# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-04 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_auto_20180104_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='size',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='磁盘大小/G'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='pn',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='厂商'),
        ),
    ]
