# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20180104_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='kernel',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='系统内核'),
        ),
        migrations.AlterField(
            model_name='host',
            name='mem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db.Memory', verbose_name='MEM/M'),
        ),
    ]
