# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20180108_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='服务器主机名'),
        ),
    ]
