# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_auto_20180108_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='locator',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='插槽'),
        ),
    ]
