# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20180108_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='uuid',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='uuid'),
        ),
    ]
