# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_auto_20180108_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='login_port',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='ssh登录端口'),
        ),
    ]
