# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-09 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_auto_20180108_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='login_port',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='ssh登录端口'),
        ),
    ]
