# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-09 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0015_auto_20180109_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='path',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='挂载路径'),
        ),
    ]
