# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_auto_20180109_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='eth0_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eth0', to='db.Network', verbose_name='eth0IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='eth1_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eth1', to='db.Network', verbose_name='eth1IP'),
        ),
        migrations.AlterField(
            model_name='host',
            name='login_pwd',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='登录密码'),
        ),
    ]
